<a href="https://colab.research.google.com/github/dinchen0626/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 格點

In [ ]:
import numpy as np

In [ ]:
x = np.array([1, 2, 3])

In [ ]:
x

array([1, 2, 3])

In [ ]:
y = np.arange(10)

In [ ]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 基本運算

In [ ]:
a = np.array([1, 2, 3, 6])

In [ ]:
b = np.linspace(0, 2, 4)

In [ ]:
c = a - b

In [ ]:
c

array([1.        , 1.33333333, 1.66666667, 4.        ])

In [ ]:
a**2

array([ 1,  4,  9, 36])

# 全域方法

In [ ]:
a = np.linspace(-np.pi, np.pi, 100)

In [ ]:
b = np.sin(a)

In [ ]:
c = np.cos(a)

# 線性代數

In [ ]:
from numpy.random import rand

In [ ]:
from numpy.linalg import solve, inv

In [ ]:
a = np.array([[1, 2, 3], [3, 4, 6.7], [5, 9.0, 5]])

In [ ]:
a.transpose()

array([[1. , 3. , 5. ],
       [2. , 4. , 9. ],
       [3. , 6.7, 5. ]])

In [ ]:
inv(a)

array([[-2.27683616,  0.96045198,  0.07909605],
       [ 1.04519774, -0.56497175,  0.1299435 ],
       [ 0.39548023,  0.05649718, -0.11299435]])

In [ ]:
b =  np.array([3, 2, 1])

In [ ]:
solve(a, b)

array([-4.83050847,  2.13559322,  1.18644068])

In [ ]:
c = rand(3, 3)

In [ ]:
c

array([[0.80235527, 0.87854552, 0.85851913],
       [0.96505793, 0.52874671, 0.16003361],
       [0.55412272, 0.41839034, 0.06478877]])

In [ ]:
np.dot(a, c)

array([[ 4.39483928,  3.19120995,  1.37295266],
       [ 9.97991974,  7.55383866,  3.6497766 ],
       [15.46791133, 11.24339969,  6.05684199]])